name: Test account service

on:
  pull:
    branches: [ main, develop ]
  pull_requests:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout account-service
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci
        run: npm run test