name: Test account service

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: tests
    steps:
      - name: Deploy dev
        run: echo "Deploy dev"

  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: deploy-dev
    steps:
      - name: Deploy prd
        run: echo "Deploy prd"
